from enum import Enum

class ResponseSignal(Enum):
    FILE_TYPE_NOT_ALLOWED = "FILE_TYPE_NOT_ALLOWED"
    FILE_SIZE_EXCEEDS_ = "FILE_SIZE_EXCEEDS_LIMIT"
    FILE_VALIDATED_SUCCESSFULLY = "FILE_VALIDATED_SUCCESSFULLY"
    FILE_UPLOAD_FAILED = "FILE_UPLOAD_FAILED"
    FILE_UPLOAD_SUCCESS = "FILE_UPLOAD_SUCCESS"
    PROCESSING_FAILED = "PROCESSING_FAILED"
    PROCESSING_SUCCESS = "PROCESSING_SUCCESS"
